### PR TITLE
Add 🤷️🙇️

### PR DESCRIPTION
**Pull request by Slymeball**
emoji | aliases
:-: | :--
🤷🏼 | "shrug"
🙇🏼 | "bow"

### CODE REVIEW

**Comment by Slymeball** [comment]
god fucking damnit

**Comment by Slymeball** [comment]
ok technically [this passes now](https://github.com/FiguraMC/Assets/actions/runs/6922684567/job/18829699696) but the action failed to update the comment

**Comment by ElectricDaFearox** [comment]
that action failed was crazy

**Comment by Slymeball** [comment]
> that action failed was crazy

yeah turns out it's hard to spot a `0` that's supposed to be an `E`

**Pull request merged**
